[package]
name = "silver-oxide"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "0.8.5"
num = "0.4.3"
indexmap = "2.13.0"
typed-index-collections = "3.5.0"
derive_more = "0.99"
derive-where = "1.2"
z3 = "0.19.15"
egg = "0.11.0"
nonmax = "0.5.5"
lasso = "0.7.3"
petgraph = "0.6"
rusttyc = "0.5.0"
im = "15.1.0"
itertools = "0.13"
rustc-hash = "2"
